version: "3"
volumes:
  db-store:
services:
  app:
    tty: true
    ports:
      - 3000:8080
    volumes:
      - type: bind
        source: "./spring-boot-demo"
        target: "/work/maven"
    env_file: ./.env
    build:
      context: ./backend
      dockerfile: ./app/Dockerfile
      args:
        OWNER_USER_ID: ${OWNER_USER_ID}
        OWNER_GROUP_ID: ${OWNER_USER_ID}
        DB_CONNECTION: mysql
  
  db:
    ports:
      - ${DB_EXT_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    env_file: ./.env
    build:
      context: ./backend
      dockerfile: ./db/mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME:-spring_local}
      - MYSQL_USER=${DB_USER:-javarista}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
